# menu
menu:
  Home: .
  Categories: categories  # 分类
  Tags: tags  # 标签
  Archives: archives  # 归档
  # Links: links  # 友链
  About: about  # 关于

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: fa-home fa-fw
  categories: fa-folder fa-fw
  tags: fa-tags fa-fw
  archives: fa-history fa-fw
  # links: icon-friendship
  about: fa-heart fa-fw

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/logo.png
  title: キスちゃま # 页面title
  favicon: /favicon.png

# config
config:
  skin: # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: false # enable posts thumbnail, options: true, false
  excerpt_link: Read More

# Pagination
pagination:
  number: false
  prev: 
    alwayShow: false
  next:
    alwayShow: false

# Sidebar
# sidebar: right
# widgets:
#   - board  
#   - category
#   - tag
#   - tagcloud
#   - archive
#   - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
# archive_type: 'monthly'
# show_count: true

# Fancybox
fancybox: false

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search
  
# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计 

# Plugins
plugins:
  
# profile
profile:
  enabled: true # Whether to show profile bar
  avatar: images/avatar.png
  author: キスちゃま
  author_title: '@kisuchama'
  location: New Million
  # Social Links
  social:
    links:
      twitter: https://twitter.com/kisuchama
      github: https://github.com/kisuchama
      # weibo: http://weibo.com/cofess      
      # facebook: /
      # dribbble: /
      # behance: https://www.behance.net/cofess
      # rss: atom.xml
    # link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills 
  # skills:
  #   Git: ★★★☆☆
  #   Gulp: ★★★☆☆
  #   Javascript: ★★★☆☆
  #   HTML+CSS: ★★★☆☆
  #   Bootstrap: ★★★☆☆
  #   ThinkPHP: ★★★☆☆
  #   平面设计: ★★★☆☆
  # # My Personal Links
  # links:
  #   Twitter: https://twitter.com/kisuchama
  #   Github: https://github.com/kisuchama   
  # My Personal Labels
  # labels:
  #   - 前端
  #   - 前端开发
  #   - 前端重构
  #   - Web前端
  #   - 网页重构
  # # My Personal Works
  # works:
  #   name:
  #     link: http://www.example.com
  #     date: 2016
  # # My Personal Projects
  # projects:
  #   cofess/gulp-startpro: https://github.com/cofess/gulp-startpro
  #   cofess/hexo-theme-pure: https://github.com/cofess/hexo-theme-pure